// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NEXTJS_ENV: string;
	WRANGLER_BUILD_CONDITIONS: string;
	WRANGLER_BUILD_PLATFORM: string;
	R2: R2Bucket;
	ASSETS: Fetcher;
}
