import type { Slide } from "@/routes/talks/-types/slide";

export const talksStorySlides: Slide[] = [
    {
        id: "typescript-never",
        title: "Demystifying the never Type in TypeScript",
        thumbnailImage: "https://picsum.photos/seed/typescript-never/960/540",
        thumbnailBlurhash: "mGSY{r%KD%?b~p9Gk8ayt7xtofWB_4xtRkoyt5D*oeof~qxtM|ay",
        pageCount: 11,
        slideUrl: "/slide/typescript-never",
        presentationUrl: "https://2024.tskaigi.org/talks/nikomaru",
        lastUpdate: "2024-05-15",
        presentationDate: "2024-05-11",
        presentationName: "TSKaigi 2024",
        tags: ["TypeScript", "Conference"],
        type: "public",
    },
    {
        id: "react-server-components",
        title: "Designing Boundaries for React Server Components",
        thumbnailImage: "https://picsum.photos/seed/react-server-components/960/540",
        thumbnailBlurhash: "mLSPX_t7M{-;?bRjRjay-;j[WBWB_3WBWBWBofj[WBay~qj[ayof",
        pageCount: 24,
        slideUrl: "/slide/react-server-components",
        presentationUrl: "https://example.com/react-server-components",
        lastUpdate: "2024-10-02",
        presentationDate: "2024-09-28",
        presentationName: "Frontend Meetup Tokyo",
        tags: ["React", "Architecture"],
        type: "public",
    },
    {
        id: "testing-ui-motion",
        title: "Testing Motion-heavy UI without Losing Confidence",
        thumbnailImage: "https://picsum.photos/seed/testing-ui-motion/960/540",
        thumbnailBlurhash: "mWQT4Mt7xu%M?bRjj[of%MRjj[of~qWBRjt7%MWBWBof4nRjxua|",
        pageCount: 8,
        slideUrl: "/slide/testing-ui-motion",
        presentationUrl: undefined,
        lastUpdate: "2025-02-19",
        presentationDate: "2025-02-18",
        presentationName: "UI Test Night",
        tags: ["Testing", "Motion"],
        type: "public",
    },
];
