import type { Locale } from "../paraglide/runtime";
import type { FileRoutesByTo } from "../routeTree.gen";

// Route paths generated by TanStack Router.
type RouteTo = keyof FileRoutesByTo;

// Translation table for route pathnames.
type TranslatedPathnames = {
    [K in RouteTo]: Record<Locale, string>;
};

// Keep pathnames in TanStack Router "to" notation for type safety.
export const translatedPathnames = {
    "/": {
        en: "/",
        ja: "/ja",
    },
    "/slides": {
        en: "/slides",
        ja: "/ja/slides",
    },
    "/slide/$": {
        en: "/slide/$",
        ja: "/ja/slide/$",
    },
} satisfies TranslatedPathnames;

function toUrlPatternPath(pathname: string): string {
    return pathname.replace(/\/\$/g, "/:_splat(.*)?").replace(/\$([A-Za-z0-9_]+)/g, ":$1");
}

// Convert translated pathnames into Paraglide urlPatterns config.
export const urlPatterns = Object.entries(translatedPathnames)
    .map(([pathname, localized]) => ({
        pattern: toUrlPatternPath(pathname),
        localized: (Object.entries(localized) as Array<[Locale, string]>).map(
            ([locale, translatedPathname]): [Locale, string] => [locale, toUrlPatternPath(translatedPathname)],
        ),
    }))
    .sort((a, b) => b.pattern.length - a.pattern.length);

const fallbackPattern = {
    pattern: "/:path(.*)?",
    localized: [
        ["en", "/:path(.*)?"],
        ["ja", "/ja/:path(.*)?"],
    ] as Array<[Locale, string]>,
};

// Ensure every path can still resolve a locale via URL strategy.
export const urlPatternsWithFallback = [...urlPatterns, fallbackPattern];
