export const sweets = [
    {
        src: "/sweets/bonbon-au-chocolat.avif",
        miniPreviewSrc: "/sweets/mini-preview/bonbon-au-chocolat.avif",
        alt: "Bonbon au chocolat",
        title: "Bonbon au chocolat",
        loading: "eager",
        blurhash: "fOI}nx_3%g_N4nRjnmtRx]9Zs;V[%Nad9Z9Fxut7OYIot6nkbFxu.8IpMxa#WBof",
    },
    {
        src: "/sweets/petit-strawberry-tart.avif",
        alt: "Petit strawberry tart",
        title: "Petit strawberry tart",
        loading: "lazy",
        blurhash: "fCJ?~ds9%gMx-;_3~W%2M{tRIUNH.7NHM_RPM{xuM_t7V?t7M{ITM_t7M{ofxvMy",
    },
    {
        src: "/sweets/souffle-pancakes.avif",
        alt: "Soufflé pancakes",
        title: "Soufflé pancakes",
        loading: "lazy",
        blurhash: "fCL{uJVs.mIpxsxutQx]Q-rrxaxttSRjITS}D%MyVrxtx]X7%gRQJ6NHr@w^x[x]",
    },
    {
        src: "/sweets/chocolate-tart.avif",
        alt: "Chocolate tart",
        title: "Chocolate tart",
        loading: "lazy",
        blurhash: "fKMHGW-=-T%24Tt7R4ozxuWAo#WB?Hoe9Faf-=ayxtWBkDayozj[MxWBxvj[Rkj]",
    },
    {
        src: "/sweets/strawberry-tart.avif",
        alt: "Strawberry tart",
        title: "Strawberry tart",
        loading: "lazy",
        blurhash: "fGIqcG?GB.tl01IqrDM|.7Ip?Gof.loz8_D*%LMx%yxt?Gt6V@xt-:xtMysl%Mxu",
    },
    {
        src: "/sweets/shortcake.avif",
        alt: "Shortcake",
        title: "Shortcake",
        loading: "lazy",
        blurhash: "fGEV.?_2xoxt%1oz?wozE0ofMxax9Gofazf5axaeNHt7V@WAtQRkx]azRjWCWXRj",
    },
    {
        src: "/sweets/napoleon-pie.avif",
        miniPreviewSrc: "/sweets/mini-preview/napoleon-pie.avif",
        alt: "Napoleon pie",
        title: "Napoleon pie",
        loading: "lazy",
        blurhash: "fgJjh{xuo#S2xut7~WofXSfjjFWVozSMt7sARPX7ofofV@V?aetRWEofRjWVozW;",
    },
    {
        src: "/sweets/creme-brulee.avif",
        alt: "Crème brûlée",
        title: "Crème brûlée",
        loading: "lazy",
        blurhash: "fDCsjht7yEogD%j[00t7IURPnha#EMt8R5oftRWBI=t6-pogtRaer=t7x]V@RiWB",
    },
    {
        src: "/sweets/mont-blanc-tart.avif",
        alt: "Mont blanc tart",
        title: "Mont blanc tart",
        loading: "lazy",
        blurhash: "fHIE;A?b_MtRITs:s,Rjt7t7Rjofx[kBDiRjxvV@s.ofWEWCRPRjIUWBoeWBxut7",
    },
] as const;
