/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AboutIndexRouteImport } from "./routes/about/index";
import { Route as ContactIndexRouteImport } from "./routes/contact/index";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SlideSplatRouteImport } from "./routes/slide/$";
import { Route as TalksIndexRouteImport } from "./routes/talks/index";
import { Route as WorksIndexRouteImport } from "./routes/works/index";

const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any);
const WorksIndexRoute = WorksIndexRouteImport.update({
    id: "/works/",
    path: "/works/",
    getParentRoute: () => rootRouteImport,
} as any);
const TalksIndexRoute = TalksIndexRouteImport.update({
    id: "/talks/",
    path: "/talks/",
    getParentRoute: () => rootRouteImport,
} as any);
const ContactIndexRoute = ContactIndexRouteImport.update({
    id: "/contact/",
    path: "/contact/",
    getParentRoute: () => rootRouteImport,
} as any);
const AboutIndexRoute = AboutIndexRouteImport.update({
    id: "/about/",
    path: "/about/",
    getParentRoute: () => rootRouteImport,
} as any);
const SlideSplatRoute = SlideSplatRouteImport.update({
    id: "/slide/$",
    path: "/slide/$",
    getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/slide/$": typeof SlideSplatRoute;
    "/about/": typeof AboutIndexRoute;
    "/contact/": typeof ContactIndexRoute;
    "/talks/": typeof TalksIndexRoute;
    "/works/": typeof WorksIndexRoute;
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/slide/$": typeof SlideSplatRoute;
    "/about": typeof AboutIndexRoute;
    "/contact": typeof ContactIndexRoute;
    "/talks": typeof TalksIndexRoute;
    "/works": typeof WorksIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    "/": typeof IndexRoute;
    "/slide/$": typeof SlideSplatRoute;
    "/about/": typeof AboutIndexRoute;
    "/contact/": typeof ContactIndexRoute;
    "/talks/": typeof TalksIndexRoute;
    "/works/": typeof WorksIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/" | "/slide/$" | "/about/" | "/contact/" | "/talks/" | "/works/";
    fileRoutesByTo: FileRoutesByTo;
    to: "/" | "/slide/$" | "/about" | "/contact" | "/talks" | "/works";
    id: "__root__" | "/" | "/slide/$" | "/about/" | "/contact/" | "/talks/" | "/works/";
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    SlideSplatRoute: typeof SlideSplatRoute;
    AboutIndexRoute: typeof AboutIndexRoute;
    ContactIndexRoute: typeof ContactIndexRoute;
    TalksIndexRoute: typeof TalksIndexRoute;
    WorksIndexRoute: typeof WorksIndexRoute;
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/works/": {
            id: "/works/";
            path: "/works";
            fullPath: "/works/";
            preLoaderRoute: typeof WorksIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/talks/": {
            id: "/talks/";
            path: "/talks";
            fullPath: "/talks/";
            preLoaderRoute: typeof TalksIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/contact/": {
            id: "/contact/";
            path: "/contact";
            fullPath: "/contact/";
            preLoaderRoute: typeof ContactIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/about/": {
            id: "/about/";
            path: "/about";
            fullPath: "/about/";
            preLoaderRoute: typeof AboutIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/slide/$": {
            id: "/slide/$";
            path: "/slide/$";
            fullPath: "/slide/$";
            preLoaderRoute: typeof SlideSplatRouteImport;
            parentRoute: typeof rootRouteImport;
        };
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    SlideSplatRoute: SlideSplatRoute,
    AboutIndexRoute: AboutIndexRoute,
    ContactIndexRoute: ContactIndexRoute,
    TalksIndexRoute: TalksIndexRoute,
    WorksIndexRoute: WorksIndexRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
    interface Register {
        ssr: true;
        router: Awaited<ReturnType<typeof getRouter>>;
    }
}
