/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalksIndexRouteImport } from './routes/talks/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PhotosIndexRouteImport } from './routes/photos/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as SlideSplatRouteImport } from './routes/slide/$'
import { Route as ProjectsProjectRouteImport } from './routes/projects/$project'
import { Route as ProjectsMineAuthIndexRouteImport } from './routes/projects/MineAuth/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksIndexRoute = TalksIndexRouteImport.update({
  id: '/talks/',
  path: '/talks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideSplatRoute = SlideSplatRouteImport.update({
  id: '/slide/$',
  path: '/slide/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMineAuthIndexRoute = ProjectsMineAuthIndexRouteImport.update({
  id: '/projects/MineAuth/',
  path: '/projects/MineAuth/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/slide/$': typeof SlideSplatRoute
  '/about/': typeof AboutIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/projects/MineAuth/': typeof ProjectsMineAuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/slide/$': typeof SlideSplatRoute
  '/about': typeof AboutIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/talks': typeof TalksIndexRoute
  '/projects/MineAuth': typeof ProjectsMineAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/slide/$': typeof SlideSplatRoute
  '/about/': typeof AboutIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/projects/MineAuth/': typeof ProjectsMineAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$project'
    | '/slide/$'
    | '/about/'
    | '/photos/'
    | '/projects/'
    | '/talks/'
    | '/projects/MineAuth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$project'
    | '/slide/$'
    | '/about'
    | '/photos'
    | '/projects'
    | '/talks'
    | '/projects/MineAuth'
  id:
    | '__root__'
    | '/'
    | '/projects/$project'
    | '/slide/$'
    | '/about/'
    | '/photos/'
    | '/projects/'
    | '/talks/'
    | '/projects/MineAuth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectRoute: typeof ProjectsProjectRoute
  SlideSplatRoute: typeof SlideSplatRoute
  AboutIndexRoute: typeof AboutIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TalksIndexRoute: typeof TalksIndexRoute
  ProjectsMineAuthIndexRoute: typeof ProjectsMineAuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/': {
      id: '/talks/'
      path: '/talks'
      fullPath: '/talks/'
      preLoaderRoute: typeof TalksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide/$': {
      id: '/slide/$'
      path: '/slide/$'
      fullPath: '/slide/$'
      preLoaderRoute: typeof SlideSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/MineAuth/': {
      id: '/projects/MineAuth/'
      path: '/projects/MineAuth'
      fullPath: '/projects/MineAuth/'
      preLoaderRoute: typeof ProjectsMineAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectRoute: ProjectsProjectRoute,
  SlideSplatRoute: SlideSplatRoute,
  AboutIndexRoute: AboutIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TalksIndexRoute: TalksIndexRoute,
  ProjectsMineAuthIndexRoute: ProjectsMineAuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
